### ISSUE TITLE
There is no notification about the restrictions on work from the container

### ISSUE THREAD

**Issue by ienrene** [martianch/curieux#4]
### Description

Can't drag images if programm works from the COMODO Antivirus Container. The cursor shows sign of ban **Ø** (a circle crossed by a diagonal slash). and the program does not inform the user about the problems and does not suggest running without a container

### Steps to reproduce
1. Run x3dview.bat  in the COMODO Antivirus Container 
2. open https://mars.nasa.gov/msl/multimedia/raw-images/?order=sol+desc%2Cinstrument_sort+asc%2Csample_type_sort+asc%2C+date_taken+desc&per_page=50&page=0&mission=msl
in Google Chrome
3. Drag a thumbnail to the x3dview's window

Expected: the notification about restrictions on work from the container, the program informs the user about the problems and suggests running without a container
Actual:  the program does not inform the user about the problems and does not suggest running without a container

### Version info
x3dview version: v0.5.1
Windows version: 8.1 64-bit
Java version: "14.0.1" 2020-04-14
Anti-virus: COMODO Antivirus 12.1.0.6914

### Stack trace
can accept: java.awt.datatransfer.DataFlavor[mimetype=application/x-java-seriali
zed-object;representationclass=java.lang.String]
importData(
false,
JUST_THIS,
sun.awt.datatransfer.ClipboardTransferable@12024a97
)
java.io.IOException: Exception fetching data:
        at java.desktop/sun.awt.datatransfer.ClipboardTransferable.getTransferDa
ta(ClipboardTransferable.java:156)
        at com.github.martianch.curieux.X3DViewer.doImportData(Main.java:911)
        at com.github.martianch.curieux.X3DViewer.doPaste(Main.java:888)
        at com.github.martianch.curieux.X3DViewer.lambda$createViews$2(Main.java
:603)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractB
utton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Abstr
actButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Defau
ltButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonM
odel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:3
69)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenu
ItemUI.java:1020)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseRele
ased(BasicMenuItemUI.java:1064)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636
)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java
:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6401)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012
)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321
)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Contai
ner.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Contain
er.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.j
ava:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307
)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:77
2)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessControlle
r.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doInt
ersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doInt
ersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessControlle
r.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doInt
ersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Even
tDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDi
spatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Even
tDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThr
ead.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThr
ead.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.jav
a:90)
Caused by: java.io.IOException: system clipboard data unavailable
        at java.desktop/sun.awt.windows.WClipboard.getClipboardData(Native Metho
d)
        at java.desktop/sun.awt.datatransfer.ClipboardTransferable.fetchOneFlavo
r(ClipboardTransferable.java:107)
        at java.desktop/sun.awt.datatransfer.ClipboardTransferable.lambda$new$0(
ClipboardTransferable.java:90)
        at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1131)
        at java.desktop/sun.awt.datatransfer.ClipboardTransferable.<init>(Clipbo
ardTransferable.java:90)
        at java.desktop/sun.awt.datatransfer.SunClipboard.getContents(SunClipboa
rd.java:138)
        at com.github.martianch.curieux.X3DViewer.doPaste(Main.java:886)
        ... 38 more
DnD transfer failed
{ transfer offered in flavors
java.awt.datatransfer.DataFlavor[mimetype=application/x-java-serialized-object;r
epresentationclass=java.lang.String]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io
.Reader]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.la
ng.String]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.ni
o.CharBuffer]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[C]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io
.InputStream;charset=unicode]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.ni
o.ByteBuffer;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;char
set=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io
.InputStream;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.ni
o.ByteBuffer;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;char
set=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io
.InputStream;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.ni
o.ByteBuffer;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;char
set=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io
.InputStream;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.ni
o.ByteBuffer;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;char
set=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io
.InputStream;charset=windows-1251]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io
.InputStream;charset=windows-1251]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.ni
o.ByteBuffer;charset=windows-1251]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;char
set=windows-1251]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io
.InputStream;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.ni
o.ByteBuffer;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;char
set=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io
.InputStream;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.ni
o.ByteBuffer;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;char
set=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=application/x-java-text-encoding;repre
sentationclass=[B]
} transfer offered in flavors

**Comment by martianch** [comment]
please check the new release v0.5.2 and tell me if this helps

**Comment by ienrene** [comment]
this bug has not been fixed
